version: 2.1

jobs:
  hello-job:
    docker:
      - image: cimg/node:19.4.0
    steps:
      - checkout
      - run: node --version
  bye-job:
    docker:
      - image: cimg/node:19.4.0
    steps:
      - checkout
      - run: ls -lh

workflows:
  my-workflow:
    jobs:
      - hello-job
